### ISSUE TITLE
App ID & Secret visible to public

### ISSUE THREAD

**Issue by berndverst** [michhar/ms-pythonbot#1]
Your code is importing an unlisted/secret GIST which actually contains your secret credentials.

https://github.com/michhar/ms-pythonbot/blob/76e627b45d903cee6afe81d3437090b207dd3efd/msbot/__init__.py#L21

This GIST has the credentials:
https://gist.github.com/michhar/d51d5fa5d4a3ec8f9b73e9d47db906b4/

**Comment by michhar** [comment]
@berndverst Thanks!  deleted.
